import { type City } from "./types";

export const cities: City[] = [
  { name: "Tartu", countryCode: "EE" },
  { name: "Tallinn", countryCode: "EE" },
  { name: "Pärnu", countryCode: "EE" },
  { name: "Narva", countryCode: "EE" },
  { name: "Kohtla-Järve", countryCode: "EE" },
  { name: "Viljandi", countryCode: "EE" },
  { name: "Rakvere", countryCode: "EE" },
  { name: "Maardu", countryCode: "EE" },
  { name: "Jõhvi", countryCode: "EE" },
  { name: "Keila", countryCode: "EE" },
  { name: "Sillamäe", countryCode: "EE" },
  { name: "Valga", countryCode: "EE" },
  { name: "Paide", countryCode: "EE" },
  { name: "Elva", countryCode: "EE" },
  { name: "Kunda", countryCode: "EE" },
  { name: "Põltsamaa", countryCode: "EE" },
  { name: "Türi", countryCode: "EE" },
  { name: "Harku", countryCode: "EE" },
  { name: "Rae", countryCode: "EE" },
  { name: "Jüri", countryCode: "EE" },
  { name: "London", countryCode: "GB" },
  { name: "Paris", countryCode: "FR" },
  { name: "Berlin", countryCode: "DE" },
  { name: "Madrid", countryCode: "ES" },
  { name: "Rome", countryCode: "IT" },
  { name: "Amsterdam", countryCode: "NL" },
  { name: "Vienna", countryCode: "AT" },
  { name: "Brussels", countryCode: "BE" },
  { name: "Zurich", countryCode: "CH" },
  { name: "Prague", countryCode: "CZ" },
  { name: "Budapest", countryCode: "HU" },
  { name: "Warsaw", countryCode: "PL" },
  { name: "Stockholm", countryCode: "SE" },
  { name: "Copenhagen", countryCode: "DK" },
  { name: "Lisbon", countryCode: "PT" },
  { name: "Dublin", countryCode: "IE" },
  { name: "Helsinki", countryCode: "FI" },
  { name: "Oslo", countryCode: "NO" },
  { name: "Edinburgh", countryCode: "GB" },
  { name: "Barcelona", countryCode: "ES" },
  { name: "Athens", countryCode: "GR" },
  { name: "New York", countryCode: "US" },
  { name: "Los Angeles", countryCode: "US" },
  { name: "Chicago", countryCode: "US" },
  { name: "Houston", countryCode: "US" },
  { name: "Philadelphia", countryCode: "US" },
  { name: "San Antonio", countryCode: "US" },
  { name: "San Diego", countryCode: "US" },
  { name: "Dallas", countryCode: "US" },
  { name: "San Jose", countryCode: "US" },
  { name: "Austin", countryCode: "US" },
  { name: "San Francisco", countryCode: "US" },
  { name: "Jacksonville", countryCode: "US" },
  { name: "Indianapolis", countryCode: "US" },
  { name: "Columbus", countryCode: "US" },
  { name: "Charlotte", countryCode: "US" },
  { name: "Tokyo", countryCode: "JP" },
  { name: "Beijing", countryCode: "CN" },
  { name: "Sydney", countryCode: "AU" },
  { name: "Dubai", countryCode: "AE" },
  { name: "Singapore", countryCode: "SG" },
  { name: "Hong Kong", countryCode: "HK" },
  { name: "Istanbul", countryCode: "TR" },
  { name: "Geneva", countryCode: "CH" },
  { name: "Munich", countryCode: "DE" },
  { name: "Hamburg", countryCode: "DE" },
  { name: "Cologne", countryCode: "DE" },
  { name: "Frankfurt", countryCode: "DE" },
  { name: "Antwerp", countryCode: "BE" },
  { name: "Ghent", countryCode: "BE" },
  { name: "Leuven", countryCode: "BE" },
  { name: "Luxembourg City", countryCode: "LU" },
  { name: "Ljubljana", countryCode: "SI" },
  { name: "Bratislava", countryCode: "SK" },
  { name: "Riga", countryCode: "LV" },
  { name: "Vilnius", countryCode: "LT" },
  { name: "Bucharest", countryCode: "RO" },
  { name: "Sofia", countryCode: "BG" },
  { name: "Belgrade", countryCode: "RS" },
  { name: "Zagreb", countryCode: "HR" },
  { name: "Sarajevo", countryCode: "BA" },
  { name: "Podgorica", countryCode: "ME" },
  { name: "Tirana", countryCode: "AL" },
  { name: "Chisinau", countryCode: "MD" },
];
